services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app
      - storage:/app/storage
    ports:
      - "3000:3000"
    command: ["bin/rails", "server", "-b", "0.0.0.0"]

  sidekiq:
    build: .
    restart: always
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
      REDIS_URL: redis://redis:6379/0
    volumes:
      - storage:/app/storage
    command: ["bundle", "exec", "sidekiq"]

volumes:
  postgres_data:
  storage:
